# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 23:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Administrators'), (2, 'Employees'), (3, 'Customers')], default=2)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male')], null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('user',),
                'verbose_name_plural': 'Users',
                'verbose_name': 'User',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, default=0, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Started'), (3, 'On Hold'), (4, 'Pending Approval'), (5, 'Completed'), (6, 'Closed')], default=1)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('latitude_register', models.FloatField(blank=True, default=0, null=True)),
                ('longitude_register', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('before_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo5', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo6', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo7', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo8', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo5', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo6', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo7', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo8', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('report', models.TextField(blank=True, null=True)),
                ('evaluation', models.IntegerField(choices=[(0, 'No Evaluation'), (1, 'Bad'), (2, 'Regular'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=0)),
                ('sign', models.FileField(blank=True, null=True, upload_to='signs/')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
            options={
                'ordering': ('-number',),
                'verbose_name_plural': 'Works',
                'verbose_name': 'Work',
                'db_table': 'works',
            },
        ),
        migrations.CreateModel(
            name='WorkEquipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Work Equipments',
                'verbose_name': 'Work Equipment',
                'db_table': 'work_equipments',
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'ordering': ('name',),
                'verbose_name_plural': 'Work Types',
                'verbose_name': 'Work Type',
                'db_table': 'work_types',
            },
        ),
        migrations.AddField(
            model_name='work',
            name='equipment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkEquipment'),
        ),
        migrations.AddField(
            model_name='work',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project'),
        ),
        migrations.AddField(
            model_name='work',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkType'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='workequipment',
            unique_together=set([('name',)]),
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([('number',)]),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([('user',)]),
        ),
    ]
