# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-19 00:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Company',
                'db_table': 'companies',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'verbose_name': 'Project',
                'verbose_name_plural': 'Projects',
                'db_table': 'projects',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Progress'), (3, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('register_datetime', models.DateTimeField(blank=True, null=True)),
                ('register_latitude', models.FloatField(blank=True, default=0, null=True)),
                ('register_longitude', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('before_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('evaluation', models.IntegerField(choices=[(0, 'No Evaluation'), (1, 'Bad'), (2, 'Regular'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=5)),
                ('sign', models.FileField(blank=True, null=True, upload_to='signs/')),
            ],
        ),
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'verbose_name': 'User Company',
                'verbose_name_plural': 'Users Companies',
                'db_table': 'users_companies',
                'ordering': ('company',),
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[(1, 'Administrators'), (2, 'Employees'), (3, 'Customers')], default=2)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('gender', models.IntegerField(blank=True, choices=[(1, 'Female'), (2, 'Male')], null=True)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('avatar', models.FileField(blank=True, null=True, upload_to='avatars/')),
                ('is_supervisor', models.BooleanField(default=False)),
                ('website', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('linkedin', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('youtube', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'ordering': ('user',),
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Project')),
                ('supervisor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
            options={
                'verbose_name': 'Work',
                'verbose_name_plural': 'Works',
                'db_table': 'works',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
            ],
            options={
                'verbose_name': 'Work Type',
                'verbose_name_plural': 'Work Types',
                'db_table': 'work_types',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='usercompany',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkType'),
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Work'),
        ),
        migrations.AddField(
            model_name='project',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AlterUniqueTogether(
            name='worktype',
            unique_together=set([('company', 'name')]),
        ),
        migrations.AlterUniqueTogether(
            name='users',
            unique_together=set([('user',)]),
        ),
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together=set([('user', 'company')]),
        ),
    ]
