# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-05 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCompany',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Company')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Users')),
            ],
            options={
                'db_table': 'users_companies',
                'verbose_name': 'User Company',
                'verbose_name_plural': 'Users Companies',
                'ordering': ('company',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='usercompany',
            unique_together=set([('user', 'company')]),
        ),
    ]
