# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-11 16:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20181105_2342'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='workequipment',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='workequipment',
            name='company',
        ),
        migrations.RemoveField(
            model_name='work',
            name='equipment',
        ),
        migrations.DeleteModel(
            name='WorkEquipment',
        ),
    ]
