# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-11 19:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20181111_1607'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='work',
            options={'ordering': ('-id',), 'verbose_name': 'Work', 'verbose_name_plural': 'Works'},
        ),
        migrations.AlterUniqueTogether(
            name='work',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='work',
            name='number',
        ),
    ]
