# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-11 20:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20181111_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('date_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'New'), (2, 'Progress'), (3, 'Completed')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('register_time', models.DateTimeField(blank=True, null=True)),
                ('latitude_register', models.FloatField(blank=True, default=0, null=True)),
                ('longitude_register', models.FloatField(blank=True, default=0, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('report', models.TextField(blank=True, null=True)),
                ('before_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('before_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo1', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo2', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo3', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('after_photo4', models.FileField(blank=True, null=True, upload_to='photos/')),
                ('evaluation', models.IntegerField(choices=[(0, 'No Evaluation'), (1, 'Bad'), (2, 'Regular'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')], default=5)),
                ('sign', models.FileField(blank=True, null=True, upload_to='signs/')),
            ],
        ),
        migrations.RenameField(
            model_name='work',
            old_name='assigned_to',
            new_name='supervisor',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo4',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo5',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo6',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo7',
        ),
        migrations.RemoveField(
            model_name='work',
            name='after_photo8',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo1',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo2',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo3',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo4',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo5',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo6',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo7',
        ),
        migrations.RemoveField(
            model_name='work',
            name='before_photo8',
        ),
        migrations.RemoveField(
            model_name='work',
            name='date_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='evaluation',
        ),
        migrations.RemoveField(
            model_name='work',
            name='latitude_register',
        ),
        migrations.RemoveField(
            model_name='work',
            name='longitude_register',
        ),
        migrations.RemoveField(
            model_name='work',
            name='register_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='report',
        ),
        migrations.RemoveField(
            model_name='work',
            name='sign',
        ),
        migrations.RemoveField(
            model_name='work',
            name='status',
        ),
        migrations.RemoveField(
            model_name='work',
            name='type',
        ),
        migrations.AddField(
            model_name='users',
            name='is_supervisor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='work',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Users'),
        ),
        migrations.AddField(
            model_name='task',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.WorkType'),
        ),
        migrations.AddField(
            model_name='task',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Work'),
        ),
    ]
