# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 16:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_task_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='is_completed',
        ),
    ]
