# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-11-14 19:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_work_is_completed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='register_time',
            new_name='register_datetime',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='latitude_register',
            new_name='register_latitude',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='longitude_register',
            new_name='register_longitude',
        ),
    ]
